### ISSUE TITLE
Bug: Checking or clicking on the "all suported fillters" on windows explorer gets rid of aero

### ISSUE THREAD

**Issue by metapea** [Faster3ck/Converseen#133]
When adding a image in windows explorer, if you click on the "all suported fillters" on the right, it disable aero in Windows 7 untill a
restart.

**Comment by Faster3ck** [comment]
Hi, this is likely a bug related to the Qt5 libraries upon which the program is built. In the latest version, I've updated the libraries, and it's possible that the issue has been resolved.

**Comment by metapea** [comment]
> Hi, this is likely a bug related to the Qt5 libraries upon which the program is built. In the latest version, I've updated the libraries, and it's possible that the issue has been resolved.

Tested it, It's still isn't working but after the first it went back to aero after flashing a black screen, the second time it flash a black screen and aero was disable still
